"""Bundle data/ into the website and render REFERENCES.md + CREDITS.md.

    python scripts/build_data.py
"""
from __future__ import annotations

import csv
import json
from collections import OrderedDict
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"


def commons_url(file: str, width: int | None = 960) -> str:
    base = "https://commons.wikimedia.org/wiki/Special:FilePath/" + quote(file.replace(" ", "_"))
    return base + (f"?width={width}" if width else "")


def commons_page(file: str) -> str:
    return "https://commons.wikimedia.org/wiki/File:" + quote(file.replace(" ", "_"))


def load(name):
    return json.loads((DATA / name).read_text(encoding="utf-8"))


def ref_link(r: dict) -> str:
    if r.get("doi"):
        return f"https://doi.org/{r['doi']}"
    return r.get("url", "")


def build_js():
    refs = load("references.json")["references"]
    images = load("images.json")["images"]
    for im in images:
        im["src"] = commons_url(im["file"])
        im["page"] = commons_page(im["file"])
    nodes = list(csv.DictReader(open(DATA / "nodes.csv", encoding="utf-8")))
    presets_path = DATA / "model_presets.json"
    presets = json.loads(presets_path.read_text(encoding="utf-8")) if presets_path.exists() else {}
    bundle = OrderedDict(
        chips=load("chips.json")["chips"],
        eras=load("timeline.json")["eras"],
        materials=load("materials.json")["materials"],
        nodes=nodes,
        images=images,
        presets=presets,
        niche=load("niche.json")["devices"],
        diamond=load("diamond.json")["milestones"],
        dopants=json.loads((DATA / "dopants.json").read_text(encoding="utf-8")) if (DATA / "dopants.json").exists() else {},
        refs=[{**r, "link": ref_link(r)} for r in refs],
    )
    js = "// Generated by scripts/build_data.py from data/*.json — do not edit by hand.\n"
    js += "export const DATA = " + json.dumps(bundle, ensure_ascii=False, separators=(",", ":")) + ";\n"
    out = ROOT / "site" / "js" / "data.js"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(js, encoding="utf-8")
    print(out.relative_to(ROOT), f"{len(js) / 1024:.0f} KB")


def build_references_md():
    refs = load("references.json")["references"]
    cats = OrderedDict()
    for r in refs:
        cats.setdefault(r["cat"], []).append(r)
    lines = ["# References", "",
             f"{len(refs)} sources, grouped by topic. Each entry carries its citation key in `code`; the key is what "
             "`data/*.json`, `docs/*.md` (as `[@key]`) and the website use. Generated from `data/references.json` by "
             "`scripts/build_data.py`; edit the JSON, not this file.", ""]
    lines.append("**Contents:** " + " · ".join(f"[{c}](#{c.lower().replace(' ', '-').replace('&', '').replace('--', '-')})" for c in cats))
    lines.append("")
    n = 0
    for cat, rs in cats.items():
        lines += [f"## {cat}", ""]
        for r in rs:
            n += 1
            link = ref_link(r)
            tail = f" [{('doi:' + r['doi']) if r.get('doi') else 'link'}]({link})" if link else ""
            lines.append(f"{n}. `{r['id']}` — {r['cite']}{tail}")
        lines.append("")
    (ROOT / "REFERENCES.md").write_text("\n".join(lines), encoding="utf-8")
    print("REFERENCES.md", n)


def build_credits_md():
    images = load("images.json")["images"]
    lines = ["# Image credits", "",
             "Photographs are loaded from Wikimedia Commons (or mirrored locally by `scripts/fetch_images.py`). "
             "Each remains under its own license; follow the source link for full author and license details. "
             "Cross-sections, layouts and charts in `figures/` are generated by this repository's code (MIT).", "",
             "| Image | Subject | Author | License | Source |", "|---|---|---|---|---|"]
    for im in images:
        lines.append(f"| ![]({commons_url(im['file'], 120)}) | {im['subject']} | {im['author']} | {im['license']} | "
                     f"[Commons]({commons_page(im['file'])}) |")
    (ROOT / "CREDITS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("CREDITS.md", len(images))


if __name__ == "__main__":
    build_js()
    build_references_md()
    build_credits_md()
