"""Bundle data/ into the website and render REFERENCES.md + CREDITS.md.

    python scripts/build_data.py
"""
from __future__ import annotations

import csv
import json
from collections import OrderedDict
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"


def commons_url(file: str, width: int | None = 960) -> str:
    base = "https://commons.wikimedia.org/wiki/Special:FilePath/" + quote(file.replace(" ", "_"))
    return base + (f"?width={width}" if width else "")


def commons_page(file: str) -> str:
    return "https://commons.wikimedia.org/wiki/File:" + quote(file.replace(" ", "_"))


def load(name):
    return json.loads((DATA / name).read_text(encoding="utf-8"))


def ref_link(r: dict) -> str:
    if r.get("doi"):
        return f"https://doi.org/{r['doi']}"
    return r.get("url", "")


def build_js():
    refs = load("references.json")["references"]
    images = load("images.json")["images"]
    for im in images:
        im["src"] = commons_url(im["file"])
        im["page"] = commons_page(im["file"])
    nodes = list(csv.DictReader(open(DATA / "nodes.csv", encoding="utf-8")))
    presets_path = DATA / "model_presets.json"
    presets = json.loads(presets_path.read_text(encoding="utf-8")) if presets_path.exists() else {}
    bundle = OrderedDict(
        chips=load("chips.json")["chips"],
        eras=load("timeline.json")["eras"],
        materials=load("materials.json")["materials"],
        nodes=nodes,
        images=images,
        presets=presets,
        niche=load("niche.json")["devices"],
        diamond=load("diamond.json")["milestones"],
        process=load("process.json")["steps"] if (DATA / "process.json").exists() else [],
        dopants=json.loads((DATA / "dopants.json").read_text(encoding="utf-8")) if (DATA / "dopants.json").exists() else {},
        refs=[{**r, "link": ref_link(r)} for r in refs],
    )
    js = "// Generated by scripts/build_data.py from data/*.json — do not edit by hand.\n"
    js += "export const DATA = " + json.dumps(bundle, ensure_ascii=False, separators=(",", ":")) + ";\n"
    out = ROOT / "site" / "js" / "data.js"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(js, encoding="utf-8")
    print(out.relative_to(ROOT), f"{len(js) / 1024:.0f} KB")
    # Physics Lab: crystal structures + the references it cites
    cpath = DATA / "crystals.json"
    if cpath.exists():
        phys_keys = {r["id"] for r in refs if r["cat"] == "Physics lab"} | {"sze2006", "taur2013", "lundstrom2017", "shockley1949", "robertson2006", "esaki1958", "frank2001", "ambacher1999", "ambacher2000", "mishra2002", "felbinger2007", "gan_diamond_tbr", "gan_diamond_tbr2021", "levinson2019", "bakshi2018", "asml_euv", "hisamoto2000"}
        pj = "// Generated by scripts/build_data.py — do not edit by hand.\n"
        pj += "export const CRYSTALS = " + cpath.read_text(encoding="utf-8") + ";\n"
        pj += "export const REFS = " + json.dumps({r["id"]: {**r, "link": ref_link(r)} for r in refs if r["id"] in phys_keys}, ensure_ascii=False, separators=(",", ":")) + ";\n"
        po = ROOT / "site" / "js" / "physics" / "data.js"
        po.write_text(pj, encoding="utf-8")
        print(po.relative_to(ROOT), f"{len(pj) / 1024:.0f} KB")
    # Circuit Lab page: memory scaling data and the references it cites
    mpath = DATA / "memory.json"
    if mpath.exists():
        mem = json.loads(mpath.read_text(encoding="utf-8"))
        ckeys = {r["id"] for r in refs if r["cat"] == "Circuit lab"} | {k for row in mem["sram"] + mem["nand"] for k in row["refs"]} \
            | {"kahng1967", "rabaey2003", "weste2010", "tanaka2007", "bardeen1948", "kilby1964"}
        cj = "// Generated by scripts/build_data.py from data/memory.json — do not edit by hand.\n"
        cj += "export const MEMORY = " + json.dumps({k: v for k, v in mem.items() if not k.startswith("_")}, ensure_ascii=False, separators=(",", ":")) + ";\n"
        cj += "export const REFS = " + json.dumps({r["id"]: {**r, "link": ref_link(r)} for r in refs if r["id"] in ckeys}, ensure_ascii=False, separators=(",", ":")) + ";\n"
        co = ROOT / "site" / "js" / "circuitlab" / "data.js"
        co.parent.mkdir(parents=True, exist_ok=True)
        co.write_text(cj, encoding="utf-8")
        print(co.relative_to(ROOT), f"{len(cj) / 1024:.0f} KB")
    # Process Lab page: wafer economics and the references it cites
    fpath = DATA / "fab_economics.json"
    if fpath.exists():
        fab = json.loads(fpath.read_text(encoding="utf-8"))
        pkeys = {r["id"] for r in refs if r["cat"] == "Process lab"} | {"plummer2000", "caughey1967", "sze2006"}
        fj = "// Generated by scripts/build_data.py from data/fab_economics.json — do not edit by hand.\n"
        fj += "export const FAB = " + json.dumps({k: v for k, v in fab.items() if not k.startswith("_")}, ensure_ascii=False, separators=(",", ":")) + ";\n"
        fj += "export const REFS = " + json.dumps({r["id"]: {**r, "link": ref_link(r)} for r in refs if r["id"] in pkeys}, ensure_ascii=False, separators=(",", ":")) + ";\n"
        fo = ROOT / "site" / "js" / "processlab" / "data.js"
        fo.parent.mkdir(parents=True, exist_ok=True)
        fo.write_text(fj, encoding="utf-8")
        print(fo.relative_to(ROOT), f"{len(fj) / 1024:.0f} KB")
    # Analog & RF Lab page: speed records and the references it cites
    rpath = DATA / "rf_records.json"
    if rpath.exists():
        rf = json.loads(rpath.read_text(encoding="utf-8"))
        akeys = {r["id"] for r in refs if r["cat"] == "Analog & RF lab"} | {"taur2013", "rabaey2003"}
        aj = "// Generated by scripts/build_data.py from data/rf_records.json — do not edit by hand.\n"
        aj += "export const RF = " + json.dumps(rf["records"], ensure_ascii=False, separators=(",", ":")) + ";\n"
        aj += "export const REFS = " + json.dumps({r["id"]: {**r, "link": ref_link(r)} for r in refs if r["id"] in akeys}, ensure_ascii=False, separators=(",", ":")) + ";\n"
        ao = ROOT / "site" / "js" / "analoglab" / "data.js"
        ao.parent.mkdir(parents=True, exist_ok=True)
        ao.write_text(aj, encoding="utf-8")
        print(ao.relative_to(ROOT), f"{len(aj) / 1024:.0f} KB")
    # Device atlas page: devices, band alignment and the references they cite
    dpath, apath = DATA / "devices.json", DATA / "band_alignment.json"
    if dpath.exists() and apath.exists():
        devs = json.loads(dpath.read_text(encoding="utf-8"))["devices"]
        align = json.loads(apath.read_text(encoding="utf-8"))
        used = {k for d in devs for k in d["refs"]} | {k for m in align["materials"] for k in m["refs"]}
        dj = "// Generated by scripts/build_data.py from data/devices.json and data/band_alignment.json — do not edit by hand.\n"
        dj += "export const DEVICES = " + json.dumps(devs, ensure_ascii=False, separators=(",", ":")) + ";\n"
        dj += "export const ALIGN = " + json.dumps(align, ensure_ascii=False, separators=(",", ":")) + ";\n"
        dj += "export const REFS = " + json.dumps({r["id"]: {**r, "link": ref_link(r)} for r in refs if r["id"] in used}, ensure_ascii=False, separators=(",", ":")) + ";\n"
        do = ROOT / "site" / "js" / "devices" / "data.js"
        do.parent.mkdir(parents=True, exist_ok=True)
        do.write_text(dj, encoding="utf-8")
        print(do.relative_to(ROOT), f"{len(dj) / 1024:.0f} KB")


def build_references_md():
    refs = load("references.json")["references"]
    cats = OrderedDict()
    for r in refs:
        cats.setdefault(r["cat"], []).append(r)
    lines = ["# References", "",
             f"{len(refs)} sources, grouped by topic. Each entry carries its citation key in `code`; the key is what "
             "`data/*.json`, `docs/*.md` (as `[@key]`) and the website use. Generated from `data/references.json` by "
             "`scripts/build_data.py`; edit the JSON, not this file.", ""]
    lines.append("**Contents:** " + " · ".join(f"[{c}](#{c.lower().replace(' ', '-').replace('&', '').replace('--', '-')})" for c in cats))
    lines.append("")
    n = 0
    for cat, rs in cats.items():
        lines += [f"## {cat}", ""]
        for r in rs:
            n += 1
            link = ref_link(r)
            tail = f" [{('doi:' + r['doi']) if r.get('doi') else 'link'}]({link})" if link else ""
            lines.append(f"{n}. `{r['id']}` — {r['cite']}{tail}")
        lines.append("")
    (ROOT / "REFERENCES.md").write_text("\n".join(lines), encoding="utf-8")
    print("REFERENCES.md", n)


def build_credits_md():
    images = load("images.json")["images"]
    lines = ["# Image credits", "",
             "Photographs are loaded from Wikimedia Commons (or mirrored locally by `scripts/fetch_images.py`). "
             "Each remains under its own license; follow the source link for full author and license details. "
             "Cross-sections, layouts and charts in `figures/` are generated by this repository's code (MIT).", "",
             "| Image | Subject | Author | License | Source |", "|---|---|---|---|---|"]
    for im in images:
        lines.append(f"| ![]({commons_url(im['file'], 120)}) | {im['subject']} | {im['author']} | {im['license']} | "
                     f"[Commons]({commons_page(im['file'])}) |")
    (ROOT / "CREDITS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("CREDITS.md", len(images))


if __name__ == "__main__":
    build_js()
    build_references_md()
    build_credits_md()
